package:
  name: Aurora
  version: "{{ load_setup_py_data().version }}"

source:
  git_url: https://github.com/fsciortino/aurora.git

build:
  number: 1

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - python {{ python }}
    - numpy {{ numpy }}
  run:
    - python {{ python }}
    - numpy {{ numpy }}

about:
  home: https://github.com/fsciortino/aurora	
  license_file: USER_AGREEMENT.txt
  summary: Modern radial impurity transport forward model for magnetically-confined plasmas